// Exchange rates (approximate)
const IDR_TO_USD = 1 / 16300;
const IDR_TO_AED = 1 / 4440;
const SQM_TO_SQFT = 10.7639;

// === ACTIVE LAND OPTIONS (from Bali Home Immo / Gillian Goh - March 2026 PDF) ===
const landOptions = [
    // --- BINGIN ---
    {
        id: "bhi-1",
        title: "Freehold Ocean View Land - Bingin (RF7845C)",
        shortTitle: "Bingin OV RF7845C",
        location: "Bingin Residential Side, Uluwatu",
        area: "Bingin",
        filterTag: "bingin",
        landSize: 1721,
        pricePerAre: 1300000000,
        totalPrice: 22373000000,
        ownership: "Freehold (SHM) - Splitable",
        zone: "Pink Zone (Touristic)",
        zoneColor: "#e91e90",
        budgetZone: "very-high",
        roadAccess: "Available",
        facing: "Ocean View",
        frontWidth: null,
        shape: null,
        description: "One of the rare few freehold big plots left in Bingin with ocean views and touristic zoning. Strategically located in an area of high-performing Airbnb villas, well connected to the New Kuta Golf area. The plot is splitable, offering flexibility for phased development. A 3-BR freehold villa was recently sold just in front of this plot for IDR 7.5 billion. Freehold villas in Bingin are increasingly rare and typically luxury 4+ BR properties valued over $1M USD.",
        nearby: [
            "3.2km to Bingin Beach",
            "3.7km to Dreamland Beach",
            "1.4km to ATMOS Recovery & Wellness",
            "Near Mazari Villas (luxury developer)",
            "Near Villa Zyloh (high-performing Airbnb)",
            "1.7km to The Era by OXO (26-unit luxury project)",
            "Near New Kuta Golf",
            "Near Bambu Fitness",
            "Near The Istana (cliff-front meditation retreat)"
        ],
        highlights: ["Rare freehold in Bingin", "Ocean view", "Touristic zoning", "Splitable plot", "High-performing Airbnb area", "Near luxury developments"],
        photos: ["images/gilly_bingin_oceanview_rf7845c.jpg", "images/bhi/bhi1_rf7845c.png"],
        mapLink: "https://bali-home-immo.com/realestate-property/for-sale/land/freehold/uluwatu/touristic-zoning-land-for-sale-freehold-leasehold-with-ocean-view-in-bingin-rf7845c",
        mapCoords: { lat: -8.812, lng: 115.128 },
        source: "Gillian Goh / Bali Home Immo",
        rentalPrice: null
    },
    {
        id: "bhi-2",
        title: "Freehold Ocean View Land - Bingin Compound (RF7845D)",
        shortTitle: "Bingin OV RF7845D",
        location: "Bingin Residential Side, Uluwatu",
        area: "Bingin",
        filterTag: "bingin",
        landSize: 2075,
        pricePerAre: 1300000000,
        totalPrice: 26975000000,
        ownership: "Freehold + Leasehold - Splitable",
        zone: "Pink Zone (Touristic)",
        zoneColor: "#e91e90",
        budgetZone: "very-high",
        roadAccess: "Available",
        facing: "Ocean View",
        frontWidth: null,
        shape: null,
        description: "A bigger plot within the RF7845 compound in Bingin. 2,075 sqm of freehold touristic land with ocean views. Part of the same strategic compound as RF7845C, surrounded by high-performing Airbnb villas and well connected to the New Kuta Golf area. Splitable into different sizes for flexible development.",
        nearby: [
            "3.2km to Bingin Beach",
            "3.7km to Dreamland Beach",
            "1.4km to ATMOS Recovery & Wellness",
            "Near Mazari Villas (luxury developer)",
            "Near Villa Zyloh (high-performing Airbnb)",
            "1.7km to The Era by OXO (26-unit luxury project)",
            "Near New Kuta Golf"
        ],
        highlights: ["Larger plot in compound", "Freehold + Leasehold options", "Ocean view", "Touristic zoning", "Splitable", "High-performing Airbnb area"],
        photos: ["images/bhi/bhi2_rf7845d_1.png", "images/bhi/bhi2_rf7845d_2.png"],
        mapLink: "https://bali-home-immo.com/realestate-property/for-sale/land/freehold/uluwatu/touristic-zoning-land-for-sale-freehold-leasehold-with-ocean-view-in-bingin-rf7845d",
        mapCoords: { lat: -8.813, lng: 115.129 },
        source: "Gillian Goh / Bali Home Immo",
        rentalPrice: null
    },
    {
        id: "bhi-3",
        title: "Freehold Prime Touristic Land - Bingin (RF7835A)",
        shortTitle: "Bingin Prime RF7835A",
        location: "Bingin Residential Side, Uluwatu",
        area: "Bingin",
        filterTag: "bingin",
        landSize: 1880,
        pricePerAre: 1250000000,
        totalPrice: 23500000000,
        ownership: "Freehold (SHM) - Splitable",
        zone: "Pink Zone (Touristic)",
        zoneColor: "#e91e90",
        budgetZone: "very-high",
        roadAccess: "Available",
        facing: null,
        frontWidth: null,
        shape: null,
        description: "Prime freehold touristic land in the heart of Bingin's development hotspot, closer to the core of touristic developments than most available plots. Surrounded by amenities and just minutes from Bingin Beach and Dreamland Beach. 1km from Bambu Fitness. Ideal for villa development targeting the booming short-term rental market.",
        nearby: [
            "3 minutes to Bingin Beach",
            "5 minutes to Dreamland Beach",
            "1km to Bambu Fitness",
            "Near Bali Training Centre",
            "Near ATMOS Recovery & Wellness",
            "Near The Istana (cliff-front meditation retreat)",
            "Surrounded by high-performing villas & amenities"
        ],
        highlights: ["Prime Bingin location", "Freehold touristic zoning", "Splitable", "Heart of touristic developments", "Minutes to beaches", "Strong rental demand"],
        photos: ["images/gilly_bingin_prime_rf7835a.jpg"],
        mapLink: "https://bali-home-immo.com/realestate-property/for-sale/land/freehold/uluwatu/touristic-zoning-land-for-sale-freehold-in-bingin-rf7835a",
        mapCoords: { lat: -8.807, lng: 115.118 },
        source: "Gillian Goh / Bali Home Immo",
        rentalPrice: null
    },
    {
        id: "bhi-4",
        title: "Freehold Ocean & Golf View Land - Dreamland (RF7697)",
        shortTitle: "Dreamland Golf RF7697",
        location: "Dreamland, New Kuta Golf, Uluwatu",
        area: "Dreamland",
        filterTag: "bingin",
        landSize: 1768,
        pricePerAre: 1000000000,
        totalPrice: 17680000000,
        ownership: "Freehold",
        zone: "Pink Zone (Touristic)",
        zoneColor: "#e91e90",
        budgetZone: "very-high",
        roadAccess: "Available",
        facing: "Ocean View + Golf Course View",
        frontWidth: null,
        shape: "Irregular",
        description: "Strategic freehold touristic land directly facing the New Kuta Golf course with ocean views. Owner is open to 3x payment plan. Easily accessible to Bingin/West Bingin prime touristic areas and Ungasan (central Uluwatu main street). Near 5-star hotels and resorts such as Jumeirah. Surrounded by luxury villas within the golf course complex.",
        nearby: [
            "Directly facing New Kuta Golf Course",
            "Walking distance to Dreamland Beach",
            "Near Jumeirah hotel",
            "Easily accessible to Bingin & West Bingin",
            "Connected to Ungasan main street",
            "Surrounded by luxury villas in golf complex",
            "Near The Links Golf Villa (26 units sold out)"
        ],
        highlights: ["Ocean + Golf course view", "3x payment plan available", "Near Jumeirah", "Touristic zoning", "Strategic location", "Surrounded by luxury villas"],
        photos: ["images/bhi/bhi4_rf7697_1.png", "images/bhi/bhi4_rf7697_2.png"],
        mapLink: "https://bali-home-immo.com/realestate-property/for-sale/land/freehold/uluwatu/touristic-zoning-land-for-sale-with-ocean-view-and-directly-facing-the-golf-course-in-dreamland-rf7697",
        mapCoords: { lat: -8.795, lng: 115.098 },
        source: "Gillian Goh / Bali Home Immo",
        rentalPrice: null
    },
    {
        id: "bhi-5",
        title: "Touristic Land Leasehold - Bingin Prime (RF5279)",
        shortTitle: "Bingin LH RF5279",
        location: "Bingin, Uluwatu",
        area: "Bingin",
        filterTag: "bingin",
        landSize: 1069,
        pricePerAre: 625000000,
        totalPrice: 6681250000,
        ownership: "Leasehold",
        zone: "Pink Zone (Touristic)",
        zoneColor: "#e91e90",
        budgetZone: "high",
        roadAccess: "Available",
        facing: null,
        frontWidth: null,
        shape: null,
        description: "Touristic zoning land in prime area of Bingin available for leasehold. Splitable (minimum 5 are). Close to all the high-performing Airbnb villas along Jl. Pantai Cemongkak. Located closer to developments at the foot of the hill. Requested new buyer to build only 1-floor building and prefer for private residence.",
        nearby: [
            "~9 minutes to beach",
            "Close to high-performing Airbnb villas on Jl. Pantai Cemongkak",
            "Near touristic developments at foot of Cemongkak hill"
        ],
        highlights: ["Touristic zoning", "Splitable (min 5 are)", "Prime Bingin area", "Lower price point", "Near high-performing villas"],
        photos: ["images/bhi/bhi5_rf5279_1.png", "images/bhi/bhi5_rf5279_2.png"],
        mapLink: "https://bali-home-immo.com/realestate-property/for-sale/land/leasehold/uluwatu/touristic-zoning-land-in-prime-area-for-sale-leasehold-in-bingin-rf5279",
        mapCoords: { lat: -8.808, lng: 115.122 },
        source: "Gillian Goh / Bali Home Immo",
        rentalPrice: null
    },

    // --- PECATU ---
    {
        id: "bhi-6",
        title: "Touristic Ocean View Land Leasehold - Pecatu (RF7895)",
        shortTitle: "Pecatu OV RF7895",
        location: "Pecatu, Uluwatu",
        area: "Pecatu",
        filterTag: "pecatu",
        landSize: 1600,
        pricePerAre: 546000000,
        totalPrice: 8736000000,
        ownership: "Leasehold (27yr priority extension available)",
        zone: "Pink Zone (Touristic)",
        zoneColor: "#e91e90",
        budgetZone: "high",
        roadAccess: "Available",
        facing: "Stunning Ocean View",
        frontWidth: null,
        shape: null,
        description: "Touristic land with stunning ocean view in Pecatu, available for leasehold. Near Bulgari Resort, The Edge, and Six Senses (reopening July 2026). Close to luxury high-end ocean view villas that are starting to develop in the area. Priority extension for 27 years available at fixed price.",
        nearby: [
            "Near Bulgari Resort",
            "Near The Edge (cliff-front wedding venue)",
            "Near Six Senses (reopening July 2026)",
            "Surrounded by new luxury villa developments"
        ],
        highlights: ["Stunning ocean view", "Near 5-star establishments", "27yr priority extension", "Touristic zoning", "Growing luxury area"],
        photos: ["images/bhi/bhi6_rf7895_1.png", "images/bhi/bhi6_rf7895_2.png"],
        mapLink: "https://bali-home-immo.com/realestate-property/for-sale/land/leasehold/uluwatu/touristic-land-for-sale-leasehold-with-stunning-ocean-view-in-uluwatu-rf7895",
        mapCoords: { lat: -8.840, lng: 115.108 },
        source: "Gillian Goh / Bali Home Immo",
        rentalPrice: null
    },
    {
        id: "bhi-7",
        title: "Mix Zone Land Leasehold - Nunggalan (RF9468A)",
        shortTitle: "Nunggalan RF9468A",
        location: "Nunggalan, Uluwatu",
        area: "Nunggalan",
        filterTag: "pecatu",
        landSize: 2000,
        pricePerAre: 811800000,
        totalPrice: 16236000000,
        ownership: "Leasehold",
        zone: "Orange Zone (Mixed Use)",
        zoneColor: "#e67e22",
        budgetZone: "high",
        roadAccess: "Available",
        facing: null,
        frontWidth: null,
        shape: null,
        description: "Mix zone land in Nunggalan available for leasehold. Walking distance to Nunggalan Beach and 6 minutes from Nyang Nyang Beach. Orange zone allows for a blend of residential, commercial, and business activities. Suitable for mixed-use developments, co-working spaces, boutique hotels, or serviced apartments.",
        nearby: [
            "Walking distance to Nunggalan Beach",
            "6 min to Nyang Nyang Beach"
        ],
        highlights: ["Mixed-use zoning", "Near Nunggalan Beach", "6 min to Nyang Nyang Beach", "Flexible development options"],
        photos: ["images/bhi/bhi7_rf9468a.png"],
        mapLink: "https://bali-home-immo.com/realestate-property/for-sale/land/leasehold/uluwatu/mix-zone-land-for-sale-leasehold-in-nunggalan-rf9468a",
        mapCoords: { lat: -8.845, lng: 115.095 },
        source: "Gillian Goh / Bali Home Immo",
        rentalPrice: null
    },
    {
        id: "bhi-8",
        title: "Mix Zone Land Leasehold - Nyang Nyang (RF8483)",
        shortTitle: "Nyang Nyang RF8483",
        location: "Nyang Nyang, Uluwatu",
        area: "Nyang Nyang",
        filterTag: "pecatu",
        landSize: 2000,
        pricePerAre: 540000000,
        totalPrice: 10800000000,
        ownership: "Leasehold",
        zone: "Orange Zone (Mixed Use)",
        zoneColor: "#e67e22",
        budgetZone: "high",
        roadAccess: "Available",
        facing: null,
        frontWidth: null,
        shape: null,
        description: "Mix zone land in Nyang Nyang available for leasehold. Walking distance to Nyang Nyang Beach. Part of one of Bali's most promising areas with upcoming beach clubs, newly paved access roads, and a laid-back surf scene drawing new boutique developments.",
        nearby: [
            "Walking distance to Nyang Nyang Beach",
            "Near upcoming beach clubs",
            "Newly paved access roads"
        ],
        highlights: ["Mixed-use zoning", "Near Nyang Nyang Beach", "Upcoming area", "Lower price per are"],
        photos: ["images/bhi/bhi8_rf8483.png"],
        mapLink: "https://bali-home-immo.com/realestate-property/for-sale/land/leasehold/uluwatu/mix-zone-land-for-sale-leasehold-in-nyang-nyang-rf8483",
        mapCoords: { lat: -8.850, lng: 115.090 },
        source: "Gillian Goh / Bali Home Immo",
        rentalPrice: null
    },
    {
        id: "bhi-9",
        title: "Touristic Land Leasehold - Uluwatu (HR109)",
        shortTitle: "Uluwatu LH HR109",
        location: "Uluwatu",
        area: "Uluwatu",
        filterTag: "pecatu",
        landSize: 1210,
        pricePerAre: 812500000,
        totalPrice: 9831250000,
        ownership: "Leasehold",
        zone: "Pink Zone (Touristic)",
        zoneColor: "#e91e90",
        budgetZone: "high",
        roadAccess: "Available",
        facing: null,
        frontWidth: null,
        shape: null,
        description: "Touristic land in a quiet area of Uluwatu, one of the most promising touristic locations. Available for leasehold. Close to Nunggalan Beach (6 min) and Nyang Nyang Beach (9 min). Ideal for villa or hospitality development.",
        nearby: [
            "6 min to Nunggalan Beach",
            "9 min to Nyang Nyang Beach"
        ],
        highlights: ["Touristic zoning", "Quiet area", "Near beaches", "Promising location"],
        photos: ["images/bhi/bhi9_hr109.png"],
        mapLink: "https://bali-home-immo.com/realestate-property/for-sale/land/leasehold/uluwatu/touristic-land-for-sale-leasehold-in-uluwatu-hr109",
        mapCoords: { lat: -8.842, lng: 115.100 },
        source: "Gillian Goh / Bali Home Immo",
        rentalPrice: null
    },

    // --- BALANGAN ---
    {
        id: "bhi-10",
        title: "Freehold Touristic Ocean View - Balangan (HR075)",
        shortTitle: "Balangan OV HR075",
        location: "Balangan, Uluwatu",
        area: "Balangan",
        filterTag: "balangan",
        landSize: 3000,
        pricePerAre: 600000000,
        totalPrice: 18000000000,
        ownership: "Freehold + Leasehold available",
        zone: "Pink Zone (Touristic)",
        zoneColor: "#e91e90",
        budgetZone: "high",
        roadAccess: "Available",
        facing: "Ocean View",
        frontWidth: null,
        shape: "Rectangular",
        description: "Rare big plot freehold in Balangan with touristic zoning and ocean views. <5 min to Balangan Beach. Rectangular shape allows for spacious villas with room for amenities. Could accommodate 3-4 are villas with communal spaces like gym, shops, tennis courts, plus luxury concierge and 24/7 security. Easily accessible to Dreamland/Bingin through the New Kuta Golf access (about 10 min).",
        nearby: [
            "<5 min to Balangan Beach",
            "10 min to Dreamland/Bingin via New Kuta Golf",
            "Near Shanti Village (luxury development)",
            "Near Palm Leylines / Bellana Bali development",
            "Off-plan construction happening around Balangan"
        ],
        highlights: ["Rare freehold in Balangan", "3,000 sqm - large plot", "Ocean view", "Rectangular shape", "Touristic zoning", "FH + LH options"],
        photos: ["images/bhi/bhi10_hr075_1.png", "images/bhi/bhi10_hr075_2.png"],
        mapLink: "https://bali-home-immo.com/realestate-property/for-sale/land/freehold/uluwatu/touristic-zoning-land-for-sale-freehold-and-leasehold-with-ocean-view-in-balangan-hr075",
        mapCoords: { lat: -8.790, lng: 115.120 },
        source: "Gillian Goh / Bali Home Immo",
        rentalPrice: null
    },
    {
        id: "bhi-11",
        title: "Freehold Ocean View on Hill - Balangan (RF9418)",
        shortTitle: "Balangan Hill RF9418",
        location: "Balangan, Uluwatu",
        area: "Balangan",
        filterTag: "balangan",
        landSize: 1010,
        pricePerAre: 950000000,
        totalPrice: 9595000000,
        ownership: "Freehold",
        zone: "Pink Zone (Touristic)",
        zoneColor: "#e91e90",
        budgetZone: "very-high",
        roadAccess: "Available",
        facing: "Unobstructed Ocean View",
        frontWidth: null,
        shape: "Elevated / On the Hill",
        description: "Just listed February 2026, price dropped March 13 to IDR 9.65B. Rare freehold in the area (most are leasehold or residential zones). Located on the hill with unobstructed ocean views. Connected to New Kuta Golf (5km). A new 3-hectare sports complex (Arete Sports) coming up 180m (1 min) from this plot. Surrounded by luxury villas.",
        nearby: [
            "5km to New Kuta Golf",
            "180m to new Arete Sports complex (3 hectares, coming soon)",
            "Easily accessible to main Jimbaran-Uluwatu street in Ungasan",
            "Surrounded by luxury villas",
            "Near sport centre and amenities"
        ],
        highlights: ["Price just dropped", "Unobstructed ocean view", "Rare freehold", "On the hill - elevated", "New sports complex 180m away", "Touristic zoning"],
        photos: ["images/bhi/bhi11_rf9418_1.png", "images/bhi/bhi11_rf9418_2.png"],
        mapLink: "https://bali-home-immo.com/realestate-property/for-sale/land/freehold/uluwatu/touristic-land-for-sale-freehold-with-unobstructed-ocean-view-in-balangan-rf9418",
        mapCoords: { lat: -8.792, lng: 115.118 },
        source: "Gillian Goh / Bali Home Immo",
        rentalPrice: null
    },

    // --- UNGASAN / MELASTI ---
    {
        id: "bhi-12",
        title: "Freehold Touristic Ocean View - Melasti (RF6751)",
        shortTitle: "Melasti OV RF6751",
        location: "Melasti, Ungasan",
        area: "Melasti",
        filterTag: "ungasan",
        landSize: 1100,
        pricePerAre: 600000000,
        totalPrice: 6600000000,
        ownership: "Freehold",
        zone: "Pink Zone (Touristic)",
        zoneColor: "#e91e90",
        budgetZone: "high",
        roadAccess: "4m road",
        facing: "Ocean View",
        frontWidth: null,
        shape: "Flat",
        description: "Rare touristic pink freehold plot in Melasti. 7 min (2.3km) to Green Bowl Beach. Close to Melasti Beach, one of the top tourist destinations in Bali, where all the famous beach clubs are (White Rock, Palmilla, Tropical Temptation). Flat land with ocean views, ideal for resort, vacation rental, or dream retreat development.",
        nearby: [
            "7 min (2.3km) to Green Bowl Beach",
            "<6km to Melasti Beach & beach clubs",
            "1.7km to Rapture Surf School",
            "Near heliport close to Melasti Beach",
            "Close to paragliding at Pandawa Beach",
            "Near Loyo Bondar development",
            "1.4km to The Blossom Pandawa by Shovk"
        ],
        highlights: ["Rare touristic freehold", "Ocean view", "Flat land", "Near beach clubs", "Price negotiable", "Growing area"],
        photos: ["images/bhi/bhi12_rf6751.png"],
        mapLink: "https://bali-home-immo.com/realestate-property/for-sale/land/freehold/ungasan/touristic-land-for-sale-freehold-with-ocean-view-in-melasti-rf6751",
        mapCoords: { lat: -8.850, lng: 115.155 },
        source: "Gillian Goh / Bali Home Immo",
        rentalPrice: null
    },
    {
        id: "bhi-13",
        title: "Freehold Touristic Ocean View - Melasti (RF6752)",
        shortTitle: "Melasti OV RF6752",
        location: "Melasti, Ungasan",
        area: "Melasti",
        filterTag: "ungasan",
        landSize: 800,
        pricePerAre: 900000000,
        totalPrice: 7200000000,
        ownership: "Freehold",
        zone: "Pink Zone (Touristic)",
        zoneColor: "#e91e90",
        budgetZone: "very-high",
        roadAccess: "3m road",
        facing: "Ocean View",
        frontWidth: null,
        shape: null,
        description: "Freehold touristic plot in Melasti, 50m from RF6751 for comparison. Ocean view with touristic zoning. 5-minute ride to Green Bowl Beach. Price is negotiable. Ideal for boutique villa or luxury retreat development.",
        nearby: [
            "5 min to Green Bowl Beach",
            "50m from RF6751 (comparison plot)",
            "<6km to Melasti Beach & beach clubs",
            "Near luxury villa developments"
        ],
        highlights: ["Freehold touristic", "Ocean view", "Price negotiable", "Near Green Bowl Beach", "Comparison to RF6751"],
        photos: ["images/bhi/bhi13_rf6752.png"],
        mapLink: "https://bali-home-immo.com/realestate-property/for-sale/land/freehold/ungasan/touristic-land-for-sale-freehold-with-ocean-view-in-melasti-rf6752",
        mapCoords: { lat: -8.851, lng: 115.156 },
        source: "Gillian Goh / Bali Home Immo",
        rentalPrice: null
    },
    {
        id: "bhi-14",
        title: "Freehold Panoramic Ocean View - Ungasan (RF9690)",
        shortTitle: "Ungasan Panoramic RF9690",
        location: "West Ungasan",
        area: "Ungasan",
        filterTag: "ungasan",
        landSize: 1310,
        pricePerAre: 800000000,
        totalPrice: 10480000000,
        ownership: "Freehold + Leasehold (30yr @ IDR 18M/are/yr)",
        zone: "Pink Zone (Touristic)",
        zoneColor: "#e91e90",
        budgetZone: "high",
        roadAccess: "4m road",
        facing: "Safe Ocean View",
        frontWidth: null,
        shape: "Sloping contour",
        description: "Touristic land in West Ungasan with panoramic ocean view. Available as both freehold and leasehold (30 years at IDR 18M/are/year). Near GWK Cultural Park and Balangan Beach. Sloping contour with safe ocean views. Ideal for villa development with both ownership options available.",
        nearby: [
            "Near GWK Cultural Park",
            "Near Balangan Beach",
            "West Ungasan location"
        ],
        highlights: ["Panoramic ocean view", "FH + LH options", "Touristic zoning", "Near GWK", "30yr leasehold option"],
        photos: ["images/bhi/bhi14_rf9690_1.png", "images/bhi/bhi14_rf9690_2.png"],
        mapLink: "https://bali-home-immo.com/realestate-property/for-sale/land/freehold/ungasan/touristic-land-for-sale-freehold-and-leasehold-with-panoramic-ocean-view-in-ungasan-rf9690",
        mapCoords: { lat: -8.830, lng: 115.145 },
        source: "Gillian Goh / Bali Home Immo",
        rentalPrice: 18000000
    },

    // --- PANDAWA ---
    {
        id: "bhi-15",
        title: "Prime Oceanview Land - Near Pandawa Beach (RF5924)",
        shortTitle: "Pandawa OV RF5924",
        location: "West Pandawa, near Pandawa Beach",
        area: "Pandawa",
        filterTag: "pandawa",
        landSize: 2009,
        pricePerAre: 750000000,
        totalPrice: 15067500000,
        ownership: "Freehold + Leasehold (30yr @ IDR 20M/are/yr)",
        zone: "Pink Zone (Touristic)",
        zoneColor: "#e91e90",
        budgetZone: "high",
        roadAccess: "5m road",
        facing: "Ocean View",
        frontWidth: null,
        shape: null,
        description: "Prime oceanview land near Pandawa Beach, a perfect investment opportunity. Available as freehold and leasehold (30 years at IDR 20M/are/year). Splitable for flexible development. 5m road access. Touristic zoning ideal for resort or villa complex development.",
        nearby: [
            "Near Pandawa Beach",
            "Near Seven Sky Bali development",
            "Near Octa Sun Residence"
        ],
        highlights: ["Prime Pandawa location", "Ocean view", "Splitable", "FH + LH options", "5m road access", "Touristic zoning"],
        photos: ["images/bhi/bhi15_rf5924.png"],
        mapLink: "https://bali-home-immo.com/realestate-property/for-sale/land/freehold/pandawa/prime-oceanview-land-for-sale-near-pandawa-beach-a-perfect-investment-opportunity-rf5924",
        mapCoords: { lat: -8.845, lng: 115.175 },
        source: "Gillian Goh / Bali Home Immo",
        rentalPrice: 20000000
    },

    // --- EAST ULUWATU ---
    {
        id: "bhi-16",
        title: "Investment Land Freehold - Near Alila Uluwatu (RF3088)",
        shortTitle: "E. Uluwatu RF3088",
        location: "East Uluwatu, near Alila Uluwatu Beach",
        area: "East Uluwatu",
        filterTag: "pecatu",
        landSize: 2000,
        pricePerAre: 700000000,
        totalPrice: 14000000000,
        ownership: "Freehold",
        zone: "Pink Zone (Touristic)",
        zoneColor: "#e91e90",
        budgetZone: "high",
        roadAccess: "5m road",
        facing: null,
        frontWidth: null,
        shape: null,
        description: "Good investment land near Alila Uluwatu Beach. 2,000 sqm freehold with touristic zoning. East Uluwatu has become a magnet for digital nomads and young families seeking affordable balance of space, privacy, and proximity to international schools in Jimbaran. 5m road access.",
        nearby: [
            "Near Alila Uluwatu Beach & Resort",
            "Near international schools in Jimbaran",
            "East Uluwatu digital nomad area"
        ],
        highlights: ["Freehold", "Near Alila Uluwatu", "Touristic zoning", "5m road access", "Growing nomad area"],
        photos: ["images/bhi/bhi16_rf3088.png"],
        mapLink: "https://bali-home-immo.com/realestate-property/for-sale/land/freehold/uluwatu/good-investment-land-for-sale-freehold-in-bali-near-alila-uluwatu-beach-rf3088",
        mapCoords: { lat: -8.838, lng: 115.112 },
        source: "Gillian Goh / Bali Home Immo",
        rentalPrice: null
    }
];

// === ARCHIVED LAND OPTIONS (previous listings) ===
const archivedLandOptions = [
    // === From Gillian Goh / Bali Home Immo (original) ===
    {
        id: "gilly-1",
        title: "Freehold Ocean View Land - Bingin (RF7845C)",
        shortTitle: "Bingin OV RF7845C",
        location: "Bingin Residential Side, Uluwatu",
        area: "Bingin",
        filterTag: "bingin",
        landSize: 1721,
        pricePerAre: 1300000000,
        totalPrice: 22373000000,
        ownership: "Freehold (SHM) - Splitable",
        zone: "Pink Zone (Touristic)",
        zoneColor: "#e91e90",
        budgetZone: "very-high",
        roadAccess: "Available",
        facing: "Ocean View",
        frontWidth: null,
        shape: null,
        description: "One of the rare few freehold big plots left in Bingin with ocean views and touristic zoning. Strategically located in an area of high-performing Airbnb villas, well connected to the New Kuta Golf area. The plot is splitable, offering flexibility for phased development.",
        nearby: [
            "3.2km to Bingin Beach",
            "3.7km to Dreamland Beach",
            "1.4km to ATMOS Recovery & Wellness",
            "Near Mazari Villas (luxury developer)",
            "Near Villa Zyloh (high-performing Airbnb)",
            "1.7km to The Era by OXO (26-unit luxury project)",
            "Near New Kuta Golf",
            "Near Bambu Fitness",
            "Near The Istana (cliff-front meditation retreat)"
        ],
        highlights: ["Rare freehold in Bingin", "Ocean view", "Touristic zoning", "Splitable plot", "High-performing Airbnb area", "Near luxury developments"],
        photos: ["images/gilly_bingin_oceanview_rf7845c.jpg"],
        mapLink: "https://bali-home-immo.com/realestate-property/for-sale/land/freehold/uluwatu/touristic-zoning-land-for-sale-freehold-leasehold-with-ocean-view-in-bingin-rf7845c",
        mapCoords: { lat: -8.812, lng: 115.128 },
        source: "Gillian Goh / Bali Home Immo",
        rentalPrice: null
    },
    {
        id: "gilly-2",
        title: "Freehold Prime Touristic Land - Bingin (RF7835A)",
        shortTitle: "Bingin Prime RF7835A",
        location: "Bingin Residential Side, Uluwatu",
        area: "Bingin",
        filterTag: "bingin",
        landSize: 1880,
        pricePerAre: 1250000000,
        totalPrice: 23500000000,
        ownership: "Freehold (SHM) - Splitable",
        zone: "Pink Zone (Touristic)",
        zoneColor: "#e91e90",
        budgetZone: "very-high",
        roadAccess: "Available",
        facing: null,
        frontWidth: null,
        shape: null,
        description: "Prime freehold touristic land in the heart of Bingin's development hotspot.",
        nearby: [
            "3 minutes to Bingin Beach",
            "5 minutes to Dreamland Beach",
            "1km to Bambu Fitness",
            "Near Bali Training Centre",
            "Near ATMOS Recovery & Wellness"
        ],
        highlights: ["Prime Bingin location", "Freehold touristic zoning", "Splitable"],
        photos: ["images/gilly_bingin_prime_rf7835a.jpg"],
        mapLink: "https://bali-home-immo.com/realestate-property/for-sale/land/freehold/uluwatu/touristic-zoning-land-for-sale-freehold-in-bingin-rf7835a",
        mapCoords: { lat: -8.807, lng: 115.118 },
        source: "Gillian Goh / Bali Home Immo",
        rentalPrice: null
    },

    // === From PDF: Cledor & Mira Document ===
    {
        id: "cm-1",
        title: "Square Shape Land - Ungasan",
        shortTitle: "Square Land Ungasan",
        location: "Ungasan, Bali",
        area: "Ungasan",
        filterTag: "ungasan",
        landSize: 2000,
        pricePerAre: 415000000,
        totalPrice: 8300000000,
        ownership: "Freehold (SHM)",
        zone: "Yellow Zone (Residential)",
        zoneColor: "#f1c40f",
        budgetZone: "affordable",
        roadAccess: "Available",
        facing: null,
        frontWidth: null,
        shape: "Square",
        description: "This rare opportunity offers a 2,000 sqm square-shaped land plot in the highly desirable area of Ungasan.",
        nearby: [],
        highlights: ["Square shape - excellent for planning", "Ready to build", "Infrastructure available"],
        photos: ["images/land_page2_img1.png", "images/land_page2_img2.png"],
        mapLink: null,
        mapCoords: { lat: -8.825, lng: 115.177 },
        source: "Cledor & Mira Development PDF",
        rentalPrice: null
    },
    {
        id: "cm-2",
        title: "Ready-to-Build Land - Ungasan",
        shortTitle: "Ready-to-Build Ungasan",
        location: "Ungasan, Bali",
        area: "Ungasan",
        filterTag: "ungasan",
        landSize: 1409,
        pricePerAre: 650000000,
        totalPrice: 9158500000,
        ownership: "Freehold",
        zone: "Yellow Zone (Residential)",
        zoneColor: "#f1c40f",
        budgetZone: "affordable",
        roadAccess: "Good road access",
        facing: null,
        frontWidth: null,
        shape: null,
        description: "A prime ready-to-build land plot in the peaceful area of Ungasan.",
        nearby: [
            "~5 min to Melasti Beach",
            "~5 min to Nirmala Supermarket Ungasan",
            "~5 min to Kasih Ibu Hospital Jimbaran"
        ],
        highlights: ["Ready to build", "Peaceful area", "Close to amenities"],
        photos: ["images/land_page4_img1.png", "images/land_page4_img2.png"],
        mapLink: null,
        mapCoords: { lat: -8.830, lng: 115.175 },
        source: "Cledor & Mira Development PDF",
        rentalPrice: null
    },
    {
        id: "cm-3",
        title: "Large Land for Development - Ungasan",
        shortTitle: "Large Dev Land Ungasan",
        location: "Ungasan, Bali",
        area: "Ungasan",
        filterTag: "ungasan",
        landSize: 9700,
        pricePerAre: 335000000,
        totalPrice: 32495000000,
        ownership: "Freehold (SHM)",
        zone: "Orange Zone",
        zoneColor: "#e67e22",
        budgetZone: "high",
        roadAccess: "Public road access",
        facing: null,
        frontWidth: "~100m front, ~98m rear",
        shape: "~132m length x 100m width",
        description: "An exceptional opportunity to acquire a large freehold land plot in Ungasan. 9,700 sqm.",
        nearby: [],
        highlights: ["Massive 9,700 sqm plot", "Wide 100m frontage", "Commercial/Residential zoning"],
        photos: ["images/land_page6_img1.png", "images/land_page6_img2.png"],
        mapLink: null,
        mapCoords: { lat: -8.832, lng: 115.173 },
        source: "Cledor & Mira Development PDF",
        rentalPrice: null
    },
    {
        id: "cm-4",
        title: "Premium Coastal Land - Fairwinds Bali",
        shortTitle: "Fairwinds Premium Coastal",
        location: "Near Kempinski & Ritz-Carlton, South Bali",
        area: "Nusa Dua",
        filterTag: "pandawa",
        landSize: 10000,
        pricePerAre: null,
        pricePerSqm: 22000000,
        totalPrice: 220000000000,
        ownership: "TBD",
        zone: "Premium Coastal (Multiple categories)",
        zoneColor: "#9b59b6",
        budgetZone: "affordable",
        roadAccess: "Premium access",
        facing: "Coastal",
        frontWidth: null,
        shape: null,
        description: "Fairwinds Bali offers an exclusive opportunity to secure premium land plots near The Apurva Kempinski Bali and The Ritz-Carlton Bali.",
        nearby: ["Adjacent to The Apurva Kempinski Bali", "Near The Ritz-Carlton Bali"],
        highlights: ["Premium coastal location", "Next to 5-star resorts", "Multiple plot categories"],
        photos: ["images/land_page8_img1.png", "images/land_page9_img1.png"],
        mapLink: null,
        mapCoords: { lat: -8.831, lng: 115.189 },
        source: "Cledor & Mira Development PDF (Fairwinds Bali)",
        rentalPrice: null
    },

    // === From Robert Property Murah ===
    {
        id: "rob-1",
        title: "Ocean View Land - Pandawa",
        shortTitle: "Ocean View Pandawa",
        location: "Pandawa, South Bali",
        area: "Pandawa",
        filterTag: "pandawa",
        landSize: 3000,
        pricePerAre: 750000000,
        totalPrice: 22500000000,
        ownership: "Freehold (3 titles: 1500+750+750 sqm)",
        zone: "Pink Zone (Tourist Accommodation)",
        zoneColor: "#e91e90",
        budgetZone: "high",
        roadAccess: "5-meter road access",
        facing: "South facing",
        frontWidth: "63 meters",
        shape: null,
        description: "Freehold ocean view land in Pandawa with 3,000 sqm across 3 separate freehold titles.",
        nearby: [],
        highlights: ["Ocean view", "3 separate freehold titles", "63m frontage"],
        photos: ["images/rob1_pandawa_1.png", "images/rob1_pandawa_2.png"],
        mapLink: "https://maps.app.goo.gl/YmfsZhBrQ23MphC56",
        mapCoords: { lat: -8.8417, lng: 115.1690 },
        source: "Robert Property Murah",
        rentalPrice: null
    },
    {
        id: "rob-2",
        title: "Ocean View Near Cemongkak Beach - Pecatu",
        shortTitle: "Cemongkak Beach Pecatu",
        location: "Pecatu, near Cemongkak Beach",
        area: "Pecatu",
        filterTag: "pecatu",
        landSize: 1263,
        pricePerAre: 1750000000,
        totalPrice: 22102500000,
        ownership: "Freehold",
        zone: "Commercial/Tourism",
        zoneColor: "#e91e90",
        budgetZone: "very-high",
        roadAccess: "8-meter wide road",
        facing: "Ocean view from 2nd floor",
        frontWidth: null,
        shape: null,
        description: "Freehold ocean view land near Cemongkak Beach in Pecatu.",
        nearby: [
            "200m to Cemongkak Beach",
            "250m to El Kabron Beach Club",
            "550m to Dreamland Beach",
            "1km to Bingin Beach"
        ],
        highlights: ["8m wide road access", "Walk to beach", "Near El Kabron"],
        photos: ["images/rob2_cemongkak_1.png", "images/rob2_cemongkak_2.png"],
        mapLink: "https://maps.app.goo.gl/4M1gGqtQ9X5zBW8G6",
        mapCoords: { lat: -8.8041, lng: 115.1182 },
        source: "Robert Property Murah",
        rentalPrice: null
    },
    {
        id: "rob-3",
        title: "Luxury Plot on Cemongkak Beach - Bingin",
        shortTitle: "Luxury Bingin Beach",
        location: "Cemongkak Beach, Bingin",
        area: "Bingin",
        filterTag: "bingin",
        landSize: 920,
        pricePerAre: 1350000000,
        totalPrice: 12420000000,
        ownership: "Freehold",
        zone: "Tourism ITR",
        zoneColor: "#e91e90",
        budgetZone: "very-high",
        roadAccess: "Private road to beach",
        facing: "West facing / Sunset views",
        frontWidth: null,
        shape: null,
        description: "Premium luxury plot on Cemongkak Beach in Bingin with 150-meter private access to the beach.",
        nearby: ["150m private beach access", "Cemongkak Beach"],
        highlights: ["Private beach access", "Sunset views", "Crystal clear ocean"],
        photos: ["images/rob3_bingin_1.png", "images/rob3_bingin_2.png"],
        mapLink: "https://maps.app.goo.gl/SFuX73gWRKNQwoho6",
        mapCoords: { lat: -8.8020, lng: 115.1187 },
        source: "Robert Property Murah",
        rentalPrice: null
    },
    {
        id: "rob-4",
        title: "Full Ocean View Land - Melasti, Ungasan",
        shortTitle: "Ocean View Melasti",
        location: "Melasti, Ungasan",
        area: "Melasti / Ungasan",
        filterTag: "ungasan",
        landSize: 425,
        pricePerAre: 950000000,
        totalPrice: 4037500000,
        ownership: "Freehold",
        zone: "Yellow Zone (Residential)",
        zoneColor: "#f1c40f",
        budgetZone: "high",
        roadAccess: "Main road - asphalt",
        facing: "Ocean view",
        frontWidth: null,
        shape: "High contour, ready to build",
        description: "Freehold land in Melasti, Ungasan with full ocean view.",
        nearby: [],
        highlights: ["Full ocean view", "Main road asphalt access", "Ready to build"],
        photos: ["images/rob4_melasti_1.png", "images/rob4_melasti_2.png"],
        mapLink: "https://maps.app.goo.gl/g2KcVLr9JZuNqWuS8",
        mapCoords: { lat: -8.838, lng: 115.159 },
        source: "Robert Property Murah",
        rentalPrice: null
    },

    // === From Dicky P. ===
    {
        id: "dk-1",
        title: "Land in Batu Manik - Uluwatu",
        shortTitle: "Batu Manik Uluwatu",
        location: "Batu Manik, Uluwatu",
        area: "Uluwatu",
        filterTag: "pecatu",
        landSize: 1980,
        pricePerAre: 750000000,
        totalPrice: 14850000000,
        ownership: "HGB (convertible to Freehold SHM)",
        zone: "Mixed Zone",
        zoneColor: "#e67e22",
        budgetZone: "high",
        roadAccess: "6 meters",
        facing: null,
        frontWidth: "~35 meters",
        shape: null,
        description: "Freehold land in Batu Manik, Uluwatu. 1,980 sqm with 35m frontage and 6m road access.",
        nearby: [],
        highlights: ["35m frontage", "Convertible to Freehold", "Mixed zone flexibility"],
        photos: ["images/dk1_batumanik_1.png", "images/dk1_batumanik_2.png"],
        mapLink: "https://maps.app.goo.gl/MGeMhavc1LdyoUof9",
        mapCoords: { lat: -8.8390, lng: 115.1044 },
        source: "Agent: Dicky P.",
        rentalPrice: null
    },
    {
        id: "dk-2",
        title: "Main Road Bingin - Ocean View",
        shortTitle: "Bingin Main Road",
        location: "Uluwatu / Pecatu / Bingin",
        area: "Bingin / Pecatu",
        filterTag: "bingin",
        landSize: 2800,
        pricePerAre: 1500000000,
        totalPrice: 42000000000,
        ownership: "Freehold",
        zone: "Trade and Services",
        zoneColor: "#e74c3c",
        budgetZone: "very-high",
        roadAccess: "6 meters",
        facing: "Ocean view",
        frontWidth: "16 meters",
        shape: null,
        description: "Rare land with ocean views located along the main road of Bingin.",
        nearby: [],
        highlights: ["Main road location", "Ocean views", "Trade & Services zone"],
        photos: ["images/dk2_bingin_1.png", "images/dk2_bingin_2.png"],
        mapLink: "https://maps.app.goo.gl/wovjzJQmwWSyDQtf8",
        mapCoords: { lat: -8.8128, lng: 115.1167 },
        source: "Agent: Dicky P.",
        rentalPrice: 35000000
    },
    {
        id: "dk-3",
        title: "Near Bulgari Hotel - Pecatu",
        shortTitle: "Pecatu near Bulgari",
        location: "Pecatu, Uluwatu (near Bulgari Hotel)",
        area: "Pecatu",
        filterTag: "pecatu",
        landSize: 2000,
        pricePerAre: 650000000,
        totalPrice: 13000000000,
        ownership: "Freehold",
        zone: "Tourism Zone",
        zoneColor: "#e91e90",
        budgetZone: "high",
        roadAccess: "6 meters",
        facing: null,
        frontWidth: "25 meters",
        shape: null,
        description: "Freehold land in Pecatu Uluwatu near the prestigious Bulgari Hotel.",
        nearby: ["Near Bulgari Hotel"],
        highlights: ["Near Bulgari Hotel", "Tourism zone", "25m frontage"],
        photos: ["images/dk3_bulgari_1.png", "images/dk3_bulgari_2.png"],
        mapLink: "https://maps.app.goo.gl/iMBzi6C9bvNPhA157",
        mapCoords: { lat: -8.8366, lng: 115.1257 },
        source: "Agent: Dicky P.",
        rentalPrice: null
    },
    {
        id: "dk-4",
        title: "Premium Land - Seminyak (Jl. Cendrawasih)",
        shortTitle: "Seminyak Premium",
        location: "Jl. Cendrawasih, Seminyak",
        area: "Seminyak",
        filterTag: "seminyak",
        landSize: 5475,
        pricePerAre: 1600000000,
        totalPrice: 87600000000,
        ownership: "Freehold",
        zone: "Tourism Accommodation",
        zoneColor: "#e91e90",
        budgetZone: "very-high",
        roadAccess: "7 meters asphalt",
        facing: null,
        frontWidth: null,
        shape: null,
        description: "Premium freehold land on Jalan Cendrawasih, Seminyak.",
        nearby: [],
        highlights: ["Prime Seminyak location", "Partial purchase option (26 are)", "7m asphalt road"],
        photos: ["images/dk4_seminyak_1.png", "images/dk4_seminyak_2.png"],
        mapLink: null,
        mapCoords: null,
        source: "Agent: Dicky P.",
        rentalPrice: null
    },
    {
        id: "dk-5",
        title: "Villa Complex Land - Umalas Bumbak",
        shortTitle: "Umalas Bumbak",
        location: "Umalas Bumbak",
        area: "Umalas",
        filterTag: "seminyak",
        landSize: 2835,
        pricePerAre: 1500000000,
        totalPrice: 42525000000,
        ownership: "Freehold",
        zone: "Mixed Zone",
        zoneColor: "#e67e22",
        budgetZone: "very-high",
        roadAccess: "5 meters",
        facing: null,
        frontWidth: null,
        shape: null,
        description: "Freehold land in Umalas Bumbak, ideal for a villa complex or investment.",
        nearby: [],
        highlights: ["Villa complex potential", "Mixed zone", "30+25 year lease option"],
        photos: [],
        mapLink: "https://goo.gl/maps/MYTcAC9m2GzhUfvZ6",
        mapCoords: null,
        source: "Agent: Dicky P.",
        rentalPrice: 32000000
    },
    {
        id: "dk-6",
        title: "Business Land - Umalas Umbak",
        shortTitle: "Umalas Umbak",
        location: "Umalas Umbak",
        area: "Umalas",
        filterTag: "seminyak",
        landSize: 2500,
        pricePerAre: 1700000000,
        totalPrice: 42500000000,
        ownership: "Freehold",
        zone: "Yellow Zone",
        zoneColor: "#f1c40f",
        budgetZone: "very-high",
        roadAccess: "6.5 meters asphalt",
        facing: null,
        frontWidth: null,
        shape: null,
        description: "Freehold land in Umalas Umbak, perfect for all businesses.",
        nearby: [],
        highlights: ["All-business suitable", "6.5m asphalt road", "Yellow zone"],
        photos: ["images/dk6_umalas_1.png", "images/dk6_umalas_2.png", "images/dk6_umalas_3.png"],
        mapLink: null,
        mapCoords: null,
        source: "Agent: Dicky P.",
        rentalPrice: null
    },
    {
        id: "dk-7",
        title: "Ocean View near Savaya/Omnia - Pecatu",
        shortTitle: "Pecatu Savaya/Omnia",
        location: "Pecatu, near Savaya/Omnia Day Club",
        area: "Pecatu",
        filterTag: "pecatu",
        landSize: 2000,
        pricePerAre: 700000000,
        totalPrice: 14000000000,
        ownership: "Freehold",
        zone: "Pink Zone (Tourist Accommodation)",
        zoneColor: "#e91e90",
        budgetZone: "high",
        roadAccess: "7m asphalt main road",
        facing: "East facing / Ocean view",
        frontWidth: null,
        shape: "Sloping",
        description: "Ocean view freehold land in Pecatu near the famous Savaya/Omnia Day Club.",
        nearby: ["3 min to Uluwatu Pecatu Main Road", "3 min to Savaya/Omnia Day Club"],
        highlights: ["Ocean view", "Near Savaya/Omnia", "7m main road"],
        photos: ["images/dk7_savaya_1.png", "images/dk7_savaya_2.png", "images/dk7_savaya_3.png"],
        mapLink: null,
        mapCoords: { lat: -8.840, lng: 115.140 },
        source: "Agent: Dicky P.",
        rentalPrice: null
    },
    {
        id: "dk-8",
        title: "Near Pandawa Golf & Gunung Payung Beach",
        shortTitle: "Pandawa Golf Area",
        location: "Jl. Nusa Dua Selatan",
        area: "Pandawa / Nusa Dua",
        filterTag: "pandawa",
        landSize: 3535,
        pricePerAre: 400000000,
        totalPrice: 14140000000,
        ownership: "Freehold (SHM)",
        zone: "Pink Zone (Tourism)",
        zoneColor: "#e91e90",
        budgetZone: "affordable",
        roadAccess: "4m paved road",
        facing: "South facing",
        frontWidth: "30 meters",
        shape: "Terraced / Ngantong",
        description: "Strategic location near Gunung Payung Beach and Pandawa Golf Course.",
        nearby: ["Gunung Payung Beach", "Pandawa Golf Course"],
        highlights: ["Near Pandawa Golf", "Tourism zoning", "30m frontline"],
        photos: ["images/dk8_pandawagolf_1.png"],
        mapLink: "https://goo.gl/maps/oBZR8JDzgo3PXJXB7",
        mapCoords: { lat: -8.8292, lng: 115.1962 },
        source: "Agent: Dicky P.",
        rentalPrice: null
    },
    {
        id: "dk-9",
        title: "Premium Ocean View - Pandawa (Expatriate Villa Area)",
        shortTitle: "Pandawa Premium OV",
        location: "Kutuh, near Pandawa Beach",
        area: "Pandawa",
        filterTag: "pandawa",
        landSize: 2000,
        pricePerAre: 1000000000,
        totalPrice: 20000000000,
        ownership: "Freehold (SHM)",
        zone: "Tourist Accommodation Zone",
        zoneColor: "#e91e90",
        budgetZone: "high",
        roadAccess: "6m asphalt (3-road access)",
        facing: "Full ocean view unblocked",
        frontWidth: null,
        shape: null,
        description: "Premium land with full unblocked ocean view in the Pandawa Beach expatriate villa area.",
        nearby: ["In front of Awang Hotman Paris Villa", "Pandawa Beach area"],
        highlights: ["Full unblocked ocean view", "3-road access", "Expatriate villa area"],
        photos: ["images/dk9_pandawa_1.png", "images/dk9_pandawa_2.png"],
        mapLink: "https://maps.app.goo.gl/GAirMVnJMvEaZd9H6",
        mapCoords: { lat: -8.8451, lng: 115.1804 },
        source: "Agent: Dicky P.",
        rentalPrice: null
    },
    {
        id: "dk-10",
        title: "Full View Land - Jimbaran (Airport & Toll View)",
        shortTitle: "Jimbaran Airport View",
        location: "Jl. Goa Betel, Jimbaran",
        area: "Jimbaran",
        filterTag: "jimbaran",
        landSize: 4750,
        pricePerAre: 450000000,
        totalPrice: 21375000000,
        ownership: "Freehold (SHM)",
        zone: "Yellow Zone",
        zoneColor: "#f1c40f",
        budgetZone: "affordable",
        roadAccess: "5m road access",
        facing: "North facing",
        frontWidth: "64 meters",
        shape: "High ground position",
        description: "Land with full ocean view, airport view, and Bali Mandara Toll Road view in Jimbaran.",
        nearby: ["Airport view", "Bali Mandara Toll Road view", "Villa complex area"],
        highlights: ["64m frontage", "Ocean + Airport view", "PDAM & PLN available"],
        photos: ["images/dk10_jimbaran_1.png", "images/dk10_jimbaran_2.png"],
        mapLink: "https://goo.gl/maps/utyarwJ94h1rtMFd6",
        mapCoords: { lat: -8.8057, lng: 115.1822 },
        source: "Agent: Dicky P.",
        rentalPrice: null
    },
    {
        id: "dk-11",
        title: "Ocean View + Villa Bonus - Jimbaran",
        shortTitle: "Jimbaran + Villa Bonus",
        location: "Jl. Uluwatu II, Jimbaran (behind Max One Hotel)",
        area: "Jimbaran",
        filterTag: "jimbaran",
        landSize: 3978,
        pricePerAre: 650000000,
        totalPrice: 25857000000,
        ownership: "Freehold",
        zone: "Pink Tourism Zone",
        zoneColor: "#e91e90",
        budgetZone: "affordable",
        roadAccess: "4.5m road access",
        facing: "Full ocean view + sunset, unblocked",
        frontWidth: "~66 meters",
        shape: "Terraced contour",
        description: "Price reduced! Full unblocked ocean view and sunset land in Jimbaran behind Max One Hotel.",
        nearby: ["Behind Max One Hotel", "Many luxury villas nearby", "Electricity, water, internet available"],
        highlights: ["BONUS VILLA included", "66m frontage", "Payment plan available"],
        photos: ["images/dk11_jimbaran2_1.png", "images/dk11_jimbaran2_2.png"],
        mapLink: "https://maps.app.goo.gl/Y6DRnwLHLr8rifgcA",
        mapCoords: { lat: -8.8114, lng: 115.1584 },
        source: "Agent: Dicky P.",
        rentalPrice: null
    }
];
