// Exchange rates (approximate)
const IDR_TO_USD = 1 / 16300;
const IDR_TO_AED = 1 / 4440;
const SQM_TO_SQFT = 10.7639;

const landOptions = [
    // === From Gillian Goh / Bali Home Immo ===
    {
        id: "gilly-1",
        title: "Freehold Ocean View Land - Bingin (RF7845C)",
        shortTitle: "Bingin OV RF7845C",
        location: "Bingin Residential Side, Uluwatu",
        area: "Bingin",
        filterTag: "bingin",
        landSize: 1721,
        pricePerAre: 1300000000,
        totalPrice: 22373000000,
        ownership: "Freehold (SHM) - Splitable",
        zone: "Pink Zone (Touristic)",
        zoneColor: "#e91e90",
        budgetZone: "very-high",
        roadAccess: "Available",
        facing: "Ocean View",
        frontWidth: null,
        shape: null,
        description: "One of the rare few freehold big plots left in Bingin with ocean views and touristic zoning. Strategically located in an area of high-performing Airbnb villas, well connected to the New Kuta Golf area. The plot is splitable, offering flexibility for phased development. A 3-BR freehold villa was recently sold just in front of this plot for IDR 7.5 billion — demonstrating the area's strong market demand. Freehold villas in Bingin are increasingly rare and typically luxury 4+ BR properties valued over $1M USD.",
        nearby: [
            "3.2km to Bingin Beach",
            "3.7km to Dreamland Beach",
            "1.4km to ATMOS Recovery & Wellness",
            "Near Mazari Villas (luxury developer)",
            "Near Villa Zyloh (high-performing Airbnb)",
            "1.7km to The Era by OXO (26-unit luxury project)",
            "Near New Kuta Golf",
            "Near Bambu Fitness",
            "Near The Istana (cliff-front meditation retreat)"
        ],
        highlights: ["Rare freehold in Bingin", "Ocean view", "Touristic zoning", "Splitable plot", "High-performing Airbnb area", "Near luxury developments"],
        photos: ["images/gilly_bingin_oceanview_rf7845c.jpg"],
        mapLink: "https://bali-home-immo.com/realestate-property/for-sale/land/freehold/uluwatu/touristic-zoning-land-for-sale-freehold-leasehold-with-ocean-view-in-bingin-rf7845c",
        mapCoords: { lat: -8.802, lng: 115.118 },
        mapPin: { x: 195, y: 305 },
        source: "Gillian Goh / Bali Home Immo",
        rentalPrice: null
    },
    {
        id: "gilly-2",
        title: "Freehold Prime Touristic Land - Bingin (RF7835A)",
        shortTitle: "Bingin Prime RF7835A",
        location: "Bingin Residential Side, Uluwatu",
        area: "Bingin",
        filterTag: "bingin",
        landSize: 1880,
        pricePerAre: 1250000000,
        totalPrice: 23500000000,
        ownership: "Freehold (SHM) - Splitable",
        zone: "Pink Zone (Touristic)",
        zoneColor: "#e91e90",
        budgetZone: "very-high",
        roadAccess: "Available",
        facing: null,
        frontWidth: null,
        shape: null,
        description: "Prime freehold touristic land in the heart of Bingin's development hotspot, closer to the core of touristic developments than most available plots. Surrounded by amenities and just minutes from Bingin Beach and Dreamland Beach. The area has seen a 3-BR older villa sell for a 19-year leasehold just 700m away, demonstrating strong demand even for leasehold properties. Ideal for villa development targeting the booming short-term rental market.",
        nearby: [
            "3 minutes to Bingin Beach",
            "5 minutes to Dreamland Beach",
            "1km to Bambu Fitness",
            "Near Bali Training Centre",
            "Near ATMOS Recovery & Wellness",
            "Near The Istana (cliff-front meditation retreat)",
            "Surrounded by high-performing villas & amenities"
        ],
        highlights: ["Prime Bingin location", "Freehold touristic zoning", "Splitable", "Heart of touristic developments", "Minutes to beaches", "Strong rental demand"],
        photos: ["images/gilly_bingin_prime_rf7835a.jpg"],
        mapLink: "https://bali-home-immo.com/realestate-property/for-sale/land/freehold/uluwatu/touristic-zoning-land-for-sale-freehold-in-bingin-rf7835a",
        mapCoords: { lat: -8.798, lng: 115.120 },
        mapPin: { x: 180, y: 285 },
        source: "Gillian Goh / Bali Home Immo",
        rentalPrice: null
    },

    // === From PDF: Cledor & Mira Document ===
    {
        id: "cm-1",
        title: "Square Shape Land - Ungasan",
        shortTitle: "Square Land Ungasan",
        location: "Ungasan, Bali",
        area: "Ungasan",
        filterTag: "ungasan",
        landSize: 2000,
        pricePerAre: 415000000,
        totalPrice: 8300000000,
        ownership: "Freehold (SHM)",
        zone: "Yellow Zone (Residential)",
        zoneColor: "#f1c40f",
        budgetZone: "affordable",
        roadAccess: "Available",
        facing: null,
        frontWidth: null,
        shape: "Square",
        description: "This rare opportunity offers a 2,000 sqm square-shaped land plot in the highly desirable area of Ungasan. Ideal for investors or developers seeking a prime site for villa development or a boutique residential project. The well-proportioned square shape provides excellent flexibility for architectural planning. Ready to build with electricity and water supply available.",
        nearby: [],
        highlights: ["Square shape - excellent for planning", "Ready to build", "Infrastructure available", "Growing investment area"],
        photos: ["images/land_page2_img1.png", "images/land_page2_img2.png"],
        mapLink: null,
        mapCoords: { lat: -8.825, lng: 115.177 },
        mapPin: { x: 460, y: 440 },
        source: "Cledor & Mira Development PDF",
        rentalPrice: null
    },
    {
        id: "cm-2",
        title: "Ready-to-Build Land - Ungasan",
        shortTitle: "Ready-to-Build Ungasan",
        location: "Ungasan, Bali",
        area: "Ungasan",
        filterTag: "ungasan",
        landSize: 1409,
        pricePerAre: 650000000,
        totalPrice: 9158500000,
        ownership: "Freehold",
        zone: "Yellow Zone (Residential)",
        zoneColor: "#f1c40f",
        budgetZone: "affordable",
        roadAccess: "Good road access",
        facing: null,
        frontWidth: null,
        shape: null,
        description: "A prime ready-to-build land plot in the peaceful area of Ungasan. Total land size of 1,409 sqm offers excellent flexibility for development. Ideal for a private luxury villa, boutique villa complex, or investment property for short-term rental market. Situated within Yellow Zone allowing residential development.",
        nearby: [
            "~5 min to Melasti Beach",
            "~5 min to Nirmala Supermarket Ungasan",
            "~5 min to Kasih Ibu Hospital Jimbaran",
            "~5 min to Bukit Sunrise School",
            "~50 min to Ngurah Rai International Airport"
        ],
        highlights: ["Ready to build", "Peaceful area", "Close to amenities", "Strong rental demand"],
        photos: ["images/land_page4_img1.png", "images/land_page4_img2.png"],
        mapLink: null,
        mapCoords: { lat: -8.830, lng: 115.175 },
        mapPin: { x: 455, y: 450 },
        source: "Cledor & Mira Development PDF",
        rentalPrice: null
    },
    {
        id: "cm-3",
        title: "Large Land for Development - Ungasan",
        shortTitle: "Large Dev Land Ungasan",
        location: "Ungasan, Bali",
        area: "Ungasan",
        filterTag: "ungasan",
        landSize: 9700,
        pricePerAre: 335000000,
        totalPrice: 32495000000,
        ownership: "Freehold (SHM)",
        zone: "Orange Zone",
        zoneColor: "#e67e22",
        budgetZone: "high",
        roadAccess: "Public road access",
        facing: null,
        frontWidth: "~100m front, ~98m rear",
        shape: "~132m length x 100m width",
        description: "An exceptional opportunity to acquire a large freehold land plot in Ungasan. 9,700 sqm spanning approximately 132 meters in length with wide frontage. Located in an Orange Zone allowing residential or commercial development. Short drive to famous beaches and luxury tourism hubs of the Bukit Peninsula.",
        nearby: [],
        highlights: ["Massive 9,700 sqm plot", "Wide 100m frontage", "Commercial/Residential zoning", "Near luxury resort area"],
        photos: ["images/land_page6_img1.png", "images/land_page6_img2.png"],
        mapLink: null,
        mapCoords: { lat: -8.832, lng: 115.173 },
        mapPin: { x: 448, y: 460 },
        source: "Cledor & Mira Development PDF",
        rentalPrice: null
    },
    {
        id: "cm-4",
        title: "Premium Coastal Land - Fairwinds Bali",
        shortTitle: "Fairwinds Premium Coastal",
        location: "Near Kempinski & Ritz-Carlton, South Bali",
        area: "Nusa Dua",
        filterTag: "pandawa",
        landSize: 10000,
        pricePerAre: null,
        pricePerSqm: 22000000,
        totalPrice: 220000000000,
        ownership: "TBD",
        zone: "Premium Coastal (Multiple categories)",
        zoneColor: "#9b59b6",
        budgetZone: "affordable",
        roadAccess: "Premium access",
        facing: "Coastal",
        frontWidth: null,
        shape: null,
        description: "Fairwinds Bali offers an exclusive opportunity to secure premium land plots in one of South Bali's most prestigious coastal areas. Strategically positioned near The Apurva Kempinski Bali and The Ritz-Carlton Bali. Pricing varies: Cliff Front (Yellow) IDR 30M/sqm, Pink IDR 21M/sqm, Green IDR 22M/sqm, Red IDR 23M/sqm. Booking fee IDR 100M with balance in 3 installments within 3 months.",
        nearby: ["Adjacent to The Apurva Kempinski Bali", "Near The Ritz-Carlton Bali"],
        highlights: ["Premium coastal location", "Next to 5-star resorts", "Multiple plot categories", "1% hard cash discount available"],
        photos: ["images/land_page8_img1.png", "images/land_page9_img1.png"],
        mapLink: null,
        mapCoords: { lat: -8.810, lng: 115.225 },
        mapPin: { x: 800, y: 320 },
        source: "Cledor & Mira Development PDF (Fairwinds Bali)",
        rentalPrice: null
    },

    // === From Robert Property Murah ===
    {
        id: "rob-1",
        title: "Ocean View Land - Pandawa",
        shortTitle: "Ocean View Pandawa",
        location: "Pandawa, South Bali",
        area: "Pandawa",
        filterTag: "pandawa",
        landSize: 3000,
        pricePerAre: 750000000,
        totalPrice: 22500000000,
        ownership: "Freehold (3 titles: 1500+750+750 sqm)",
        zone: "Pink Zone (Tourist Accommodation)",
        zoneColor: "#e91e90",
        budgetZone: "high",
        roadAccess: "5-meter road access",
        facing: "South facing",
        frontWidth: "63 meters",
        shape: null,
        description: "Freehold ocean view land in Pandawa with 3,000 sqm across 3 separate freehold titles. South facing with 63m frontage and 5m road access. Located in Pink Zone for tourist accommodation development.",
        nearby: [],
        highlights: ["Ocean view", "3 separate freehold titles", "63m frontage", "Tourist accommodation zone"],
        photos: ["images/rob1_pandawa_1.png", "images/rob1_pandawa_2.png"],
        mapLink: "https://maps.app.goo.gl/YmfsZhBrQ23MphC56",
        mapCoords: { lat: -8.844, lng: 115.198 },
        mapPin: { x: 660, y: 530 },
        source: "Robert Property Murah",
        rentalPrice: null
    },
    {
        id: "rob-2",
        title: "Ocean View Near Cemongkak Beach - Pecatu",
        shortTitle: "Cemongkak Beach Pecatu",
        location: "Pecatu, near Cemongkak Beach",
        area: "Pecatu",
        filterTag: "pecatu",
        landSize: 1263,
        pricePerAre: 1750000000,
        totalPrice: 22102500000,
        ownership: "Freehold",
        zone: "Commercial/Tourism",
        zoneColor: "#e91e90",
        budgetZone: "very-high",
        roadAccess: "8-meter wide road",
        facing: "Ocean view from 2nd floor",
        frontWidth: null,
        shape: null,
        description: "Freehold ocean view land near Cemongkak Beach in Pecatu. In a developing tourist area of South Kuta surrounded by commercial villas, guesthouses, and homestays. 200m walk to beach, 250m to El Kabron Beach Club, 550m to Dreamland Beach, 1km to Bingin Beach.",
        nearby: [
            "200m to Cemongkak Beach",
            "250m to El Kabron Beach Club",
            "550m to Dreamland Beach",
            "1km to Bingin Beach"
        ],
        highlights: ["8m wide road access", "Walk to beach", "Near El Kabron", "Ready to build"],
        photos: ["images/rob2_cemongkak_1.png", "images/rob2_cemongkak_2.png"],
        mapLink: "https://maps.app.goo.gl/4M1gGqtQ9X5zBW8G6",
        mapCoords: { lat: -8.806, lng: 115.117 },
        mapPin: { x: 235, y: 310 },
        source: "Robert Property Murah",
        rentalPrice: null
    },
    {
        id: "rob-3",
        title: "Luxury Plot on Cemongkak Beach - Bingin",
        shortTitle: "Luxury Bingin Beach",
        location: "Cemongkak Beach, Bingin",
        area: "Bingin",
        filterTag: "bingin",
        landSize: 920,
        pricePerAre: 1350000000,
        totalPrice: 12420000000,
        ownership: "Freehold",
        zone: "Tourism ITR",
        zoneColor: "#e91e90",
        budgetZone: "very-high",
        roadAccess: "Private road to beach",
        facing: "West facing / Sunset views",
        frontWidth: null,
        shape: null,
        description: "Premium luxury plot on Cemongkak Beach in Bingin with 150-meter private access to the beach. West facing with stunning sunset views over crystal clear turquoise ocean. Areas starting from 920 sqm.",
        nearby: ["150m private beach access", "Cemongkak Beach"],
        highlights: ["Private beach access", "Sunset views", "Crystal clear ocean", "Premium location"],
        photos: ["images/rob3_bingin_1.png", "images/rob3_bingin_2.png"],
        mapLink: "https://maps.app.goo.gl/SFuX73gWRKNQwoho6",
        mapCoords: { lat: -8.803, lng: 115.112 },
        mapPin: { x: 210, y: 290 },
        source: "Robert Property Murah",
        rentalPrice: null
    },
    {
        id: "rob-4",
        title: "Full Ocean View Land - Melasti, Ungasan",
        shortTitle: "Ocean View Melasti",
        location: "Melasti, Ungasan",
        area: "Melasti / Ungasan",
        filterTag: "ungasan",
        landSize: 425,
        pricePerAre: 950000000,
        totalPrice: 4037500000,
        ownership: "Freehold",
        zone: "Yellow Zone (Residential)",
        zoneColor: "#f1c40f",
        budgetZone: "high",
        roadAccess: "Main road - asphalt",
        facing: "Ocean view",
        frontWidth: null,
        shape: "High contour, ready to build",
        description: "Freehold land in Melasti, Ungasan with full ocean view. Starting from 425 sqm with main asphalt road access. Residential Yellow Zone ITR, high contour and ready to build. Ideal for villa development.",
        nearby: [],
        highlights: ["Full ocean view", "Main road asphalt access", "Ready to build", "High contour"],
        photos: ["images/rob4_melasti_1.png", "images/rob4_melasti_2.png"],
        mapLink: "https://maps.app.goo.gl/g2KcVLr9JZuNqWuS8",
        mapCoords: { lat: -8.847, lng: 115.168 },
        mapPin: { x: 510, y: 610 },
        source: "Robert Property Murah",
        rentalPrice: null
    },

    // === From Dicky P. ===
    {
        id: "dk-1",
        title: "Land in Batu Manik - Uluwatu",
        shortTitle: "Batu Manik Uluwatu",
        location: "Batu Manik, Uluwatu",
        area: "Uluwatu",
        filterTag: "pecatu",
        landSize: 1980,
        pricePerAre: 750000000,
        totalPrice: 14850000000,
        ownership: "HGB (convertible to Freehold SHM)",
        zone: "Mixed Zone",
        zoneColor: "#e67e22",
        budgetZone: "high",
        roadAccess: "6 meters",
        facing: null,
        frontWidth: "~35 meters",
        shape: null,
        description: "Freehold land in Batu Manik, Uluwatu. 1,980 sqm with 35m frontage and 6m road access. Currently HGB (shared title) but can be converted to SHM (Freehold). Mixed zone ITR.",
        nearby: [],
        highlights: ["35m frontage", "Convertible to Freehold", "Mixed zone flexibility", "6m road access"],
        photos: ["images/dk1_batumanik_1.png", "images/dk1_batumanik_2.png"],
        mapLink: "https://maps.app.goo.gl/MGeMhavc1LdyoUof9",
        mapCoords: { lat: -8.815, lng: 115.130 },
        mapPin: { x: 300, y: 380 },
        source: "Agent: Dicky P.",
        rentalPrice: null
    },
    {
        id: "dk-2",
        title: "Main Road Bingin - Ocean View",
        shortTitle: "Bingin Main Road",
        location: "Uluwatu / Pecatu / Bingin",
        area: "Bingin / Pecatu",
        filterTag: "bingin",
        landSize: 2800,
        pricePerAre: 1500000000,
        totalPrice: 42000000000,
        ownership: "Freehold",
        zone: "Trade and Services",
        zoneColor: "#e74c3c",
        budgetZone: "very-high",
        roadAccess: "6 meters",
        facing: "Ocean view",
        frontWidth: "16 meters",
        shape: null,
        description: "Rare land with ocean views located along the main road of Bingin in the heart of Uluwatu/Pecatu. 2,800 sqm with freehold certificate. Trade and Services zone ITR. Also available for lease at IDR 35M/are/year.",
        nearby: [],
        highlights: ["Main road location", "Ocean views", "Trade & Services zone", "Sale or lease available"],
        photos: ["images/dk2_bingin_1.png", "images/dk2_bingin_2.png"],
        mapLink: "https://maps.app.goo.gl/wovjzJQmwWSyDQtf8",
        mapCoords: { lat: -8.800, lng: 115.115 },
        mapPin: { x: 220, y: 270 },
        source: "Agent: Dicky P.",
        rentalPrice: 35000000
    },
    {
        id: "dk-3",
        title: "Near Bulgari Hotel - Pecatu",
        shortTitle: "Pecatu near Bulgari",
        location: "Pecatu, Uluwatu (near Bulgari Hotel)",
        area: "Pecatu",
        filterTag: "pecatu",
        landSize: 2000,
        pricePerAre: 650000000,
        totalPrice: 13000000000,
        ownership: "Freehold",
        zone: "Tourism Zone",
        zoneColor: "#e91e90",
        budgetZone: "high",
        roadAccess: "6 meters",
        facing: null,
        frontWidth: "25 meters",
        shape: null,
        description: "Freehold land in Pecatu Uluwatu near the prestigious Bulgari Hotel. 2,000 sqm with 25m frontage and 6m road access. Tourism zone ITR making it ideal for commercial villa or hospitality development.",
        nearby: ["Near Bulgari Hotel"],
        highlights: ["Near Bulgari Hotel", "Tourism zone", "25m frontage", "Premium Pecatu location"],
        photos: ["images/dk3_bulgari_1.png", "images/dk3_bulgari_2.png"],
        mapLink: "https://maps.app.goo.gl/iMBzi6C9bvNPhA157",
        mapCoords: { lat: -8.820, lng: 115.140 },
        mapPin: { x: 330, y: 420 },
        source: "Agent: Dicky P.",
        rentalPrice: null
    },
    {
        id: "dk-4",
        title: "Premium Land - Seminyak (Jl. Cendrawasih)",
        shortTitle: "Seminyak Premium",
        location: "Jl. Cendrawasih, Seminyak",
        area: "Seminyak",
        filterTag: "seminyak",
        landSize: 5475,
        pricePerAre: 1600000000,
        totalPrice: 87600000000,
        ownership: "Freehold",
        zone: "Tourism Accommodation",
        zoneColor: "#e91e90",
        budgetZone: "very-high",
        roadAccess: "7 meters asphalt",
        facing: null,
        frontWidth: null,
        shape: null,
        description: "Premium freehold land on Jalan Cendrawasih, Seminyak. Total 54.75 are (5,475 sqm). Option to purchase front land only at 26.90 are. Tourism Accommodation zone with 7m asphalt road access. Global price IDR 1.6B/are negotiable; front land at IDR 1.9B/are.",
        nearby: [],
        highlights: ["Prime Seminyak location", "Partial purchase option (26 are)", "7m asphalt road", "Tourism accommodation zone"],
        photos: ["images/dk4_seminyak_1.png", "images/dk4_seminyak_2.png"],
        mapLink: null,
        mapCoords: null,
        mapPin: null,
        source: "Agent: Dicky P.",
        rentalPrice: null
    },
    {
        id: "dk-5",
        title: "Villa Complex Land - Umalas Bumbak",
        shortTitle: "Umalas Bumbak",
        location: "Umalas Bumbak",
        area: "Umalas",
        filterTag: "seminyak",
        landSize: 2835,
        pricePerAre: 1500000000,
        totalPrice: 42525000000,
        ownership: "Freehold",
        zone: "Mixed Zone",
        zoneColor: "#e67e22",
        budgetZone: "very-high",
        roadAccess: "5 meters",
        facing: null,
        frontWidth: null,
        shape: null,
        description: "Freehold land in Umalas Bumbak, ideal for a villa complex or investment. 28.35 are (2,835 sqm) with mixed zone ITR. Also available for lease at IDR 32M/are/year for 30 years + 25 year extension.",
        nearby: [],
        highlights: ["Villa complex potential", "Mixed zone", "30+25 year lease option", "Umalas lifestyle area"],
        photos: [],
        mapLink: "https://goo.gl/maps/MYTcAC9m2GzhUfvZ6",
        mapCoords: null,
        mapPin: null,
        source: "Agent: Dicky P.",
        rentalPrice: 32000000
    },
    {
        id: "dk-6",
        title: "Business Land - Umalas Umbak",
        shortTitle: "Umalas Umbak",
        location: "Umalas Umbak",
        area: "Umalas",
        filterTag: "seminyak",
        landSize: 2500,
        pricePerAre: 1700000000,
        totalPrice: 42500000000,
        ownership: "Freehold",
        zone: "Yellow Zone",
        zoneColor: "#f1c40f",
        budgetZone: "very-high",
        roadAccess: "6.5 meters asphalt",
        facing: null,
        frontWidth: null,
        shape: null,
        description: "Freehold land in Umalas Umbak, perfect for all businesses. 25 are (2,500 sqm) in Yellow Zone with 6.5m asphalt road access.",
        nearby: [],
        highlights: ["All-business suitable", "6.5m asphalt road", "Yellow zone", "Prime Umalas"],
        photos: ["images/dk6_umalas_1.png", "images/dk6_umalas_2.png", "images/dk6_umalas_3.png"],
        mapLink: null,
        mapCoords: null,
        mapPin: null,
        source: "Agent: Dicky P.",
        rentalPrice: null
    },
    {
        id: "dk-7",
        title: "Ocean View near Savaya/Omnia - Pecatu",
        shortTitle: "Pecatu Savaya/Omnia",
        location: "Pecatu, near Savaya/Omnia Day Club",
        area: "Pecatu",
        filterTag: "pecatu",
        landSize: 2000,
        pricePerAre: 700000000,
        totalPrice: 14000000000,
        ownership: "Freehold",
        zone: "Pink Zone (Tourist Accommodation)",
        zoneColor: "#e91e90",
        budgetZone: "high",
        roadAccess: "7m asphalt main road",
        facing: "East facing / Ocean view",
        frontWidth: null,
        shape: "Sloping",
        description: "Ocean view freehold land in Pecatu near the famous Savaya/Omnia Day Club. 2,000 sqm with 7m asphalt main road access. Pink zone tourist accommodation. 3 minutes from Uluwatu Pecatu main road and 3 minutes from Savaya/Omnia.",
        nearby: ["3 min to Uluwatu Pecatu Main Road", "3 min to Savaya/Omnia Day Club"],
        highlights: ["Ocean view", "Near Savaya/Omnia", "7m main road", "Tourist accommodation zone"],
        photos: ["images/dk7_savaya_1.png", "images/dk7_savaya_2.png", "images/dk7_savaya_3.png"],
        mapLink: null,
        mapCoords: { lat: -8.825, lng: 115.135 },
        mapPin: { x: 320, y: 440 },
        source: "Agent: Dicky P.",
        rentalPrice: null
    },
    {
        id: "dk-8",
        title: "Near Pandawa Golf & Gunung Payung Beach",
        shortTitle: "Pandawa Golf Area",
        location: "Jl. Nusa Dua Selatan",
        area: "Pandawa / Nusa Dua",
        filterTag: "pandawa",
        landSize: 3535,
        pricePerAre: 400000000,
        totalPrice: 14140000000,
        ownership: "Freehold (SHM)",
        zone: "Pink Zone (Tourism)",
        zoneColor: "#e91e90",
        budgetZone: "affordable",
        roadAccess: "4m paved road",
        facing: "South facing",
        frontWidth: "30 meters",
        shape: "Terraced / Ngantong",
        description: "Strategic location near Gunung Payung Beach and Pandawa Golf Course on Jl. Nusa Dua Selatan. 3,535 sqm freehold with tourism zoning (pink). Terraced land contour with 30m frontline width. Suitable for all types of residences and investment.",
        nearby: ["Gunung Payung Beach", "Pandawa Golf Course"],
        highlights: ["Near Pandawa Golf", "Tourism zoning", "30m frontline", "Terraced contour"],
        photos: ["images/dk8_pandawagolf_1.png"],
        mapLink: "https://goo.gl/maps/oBZR8JDzgo3PXJXB7",
        mapCoords: { lat: -8.845, lng: 115.210 },
        mapPin: { x: 730, y: 490 },
        source: "Agent: Dicky P.",
        rentalPrice: null
    },
    {
        id: "dk-9",
        title: "Premium Ocean View - Pandawa (Expatriate Villa Area)",
        shortTitle: "Pandawa Premium OV",
        location: "Kutuh, near Pandawa Beach",
        area: "Pandawa",
        filterTag: "pandawa",
        landSize: 2000,
        pricePerAre: 1000000000,
        totalPrice: 20000000000,
        ownership: "Freehold (SHM)",
        zone: "Tourist Accommodation Zone",
        zoneColor: "#e91e90",
        budgetZone: "high",
        roadAccess: "6m asphalt (3-road access)",
        facing: "Full ocean view unblocked",
        frontWidth: null,
        shape: null,
        description: "Premium land with full unblocked ocean view in the Pandawa Beach expatriate villa area, located in front of the famous Awang Hotman Paris Villa. 2,000 sqm (can purchase 10 are portion). Unique 3-road access from front, back, and side.",
        nearby: ["In front of Awang Hotman Paris Villa", "Pandawa Beach area"],
        highlights: ["Full unblocked ocean view", "3-road access", "Expatriate villa area", "Partial purchase available (10 are)"],
        photos: ["images/dk9_pandawa_1.png", "images/dk9_pandawa_2.png"],
        mapLink: "https://maps.app.goo.gl/GAirMVnJMvEaZd9H6",
        mapCoords: { lat: -8.840, lng: 115.195 },
        mapPin: { x: 640, y: 510 },
        source: "Agent: Dicky P.",
        rentalPrice: null
    },
    {
        id: "dk-10",
        title: "Full View Land - Jimbaran (Airport & Toll View)",
        shortTitle: "Jimbaran Airport View",
        location: "Jl. Goa Betel, Jimbaran",
        area: "Jimbaran",
        filterTag: "jimbaran",
        landSize: 4750,
        pricePerAre: 450000000,
        totalPrice: 21375000000,
        ownership: "Freehold (SHM)",
        zone: "Yellow Zone",
        zoneColor: "#f1c40f",
        budgetZone: "affordable",
        roadAccess: "5m road access",
        facing: "North facing",
        frontWidth: "64 meters",
        shape: "High ground position",
        description: "Land with full ocean view, airport view, and Bali Mandara Toll Road view in Jimbaran. 4,750 sqm with 64m frontage. Yellow zone with PDAM and PLN networks available. Villa complex area. Seller needs quick sale!",
        nearby: ["Airport view", "Bali Mandara Toll Road view", "Villa complex area"],
        highlights: ["64m frontage", "Ocean + Airport view", "PDAM & PLN available", "Urgent sale - negotiable"],
        photos: ["images/dk10_jimbaran_1.png", "images/dk10_jimbaran_2.png"],
        mapLink: "https://goo.gl/maps/utyarwJ94h1rtMFd6",
        mapCoords: { lat: -8.790, lng: 115.165 },
        mapPin: { x: 560, y: 160 },
        source: "Agent: Dicky P.",
        rentalPrice: null
    },
    {
        id: "dk-11",
        title: "Ocean View + Villa Bonus - Jimbaran",
        shortTitle: "Jimbaran + Villa Bonus",
        location: "Jl. Uluwatu II, Jimbaran (behind Max One Hotel)",
        area: "Jimbaran",
        filterTag: "jimbaran",
        landSize: 3978,
        pricePerAre: 650000000,
        totalPrice: 25857000000,
        ownership: "Freehold",
        zone: "Pink Tourism Zone",
        zoneColor: "#e91e90",
        budgetZone: "affordable",
        roadAccess: "4.5m road access",
        facing: "Full ocean view + sunset, unblocked",
        frontWidth: "~66 meters",
        shape: "Terraced contour",
        description: "Price reduced! Full unblocked ocean view and sunset land in Jimbaran behind Max One Hotel. 3,978 sqm with 66m frontage. Comes with bonus villa building. Pink Tourism zone. Payment plan available: 50% upfront, 25% at 6 months, 25% at 12 months.",
        nearby: ["Behind Max One Hotel", "Many luxury villas nearby", "Electricity, water, internet available"],
        highlights: ["BONUS VILLA included", "66m frontage", "Payment plan available", "Full ocean + sunset view"],
        photos: ["images/dk11_jimbaran2_1.png", "images/dk11_jimbaran2_2.png"],
        mapLink: "https://maps.app.goo.gl/Y6DRnwLHLr8rifgcA",
        mapCoords: { lat: -8.795, lng: 115.160 },
        mapPin: { x: 540, y: 180 },
        source: "Agent: Dicky P.",
        rentalPrice: null
    }
];
